name: Try to build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    strategy:
      max-parallel: 1
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'master'
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          # explicitly enable sandbox
          extra_nix_config: sandbox = true
      - uses: cachix/cachix-action@18cf96c7c98e048e10a83abd92116114cd8504be # v14
        with:
          name: oliver
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: "curl https://jit6.mkg20001.io | env JIT6_TOKEN=${{ secrets.JIT6_TOKEN }} bash -"
      - run: nix flake update
#      - run: nix build .#all
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "automatic updates"
          file_pattern: "flake.lock"
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
      - run: sleep 10
